#pragma once

#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#import <ReactCommon/RCTTurboModule.h>

// TescoNativeBridgeSpec.h is pre-generated by Codegen and committed to the repo
// under codegen/. It defines NativeTescoNativeBridgeSpec (ObjC protocol) and
// NativeTescoNativeBridgeSpecJSI (C++ JSI class).
#import <TescoNativeBridge/TescoNativeBridgeSpec.h>

NS_ASSUME_NONNULL_BEGIN

/// ObjC++ TurboModule that exposes onButtonTapped() to JavaScript.
///
/// JS usage (via NativeTescoNativeBridge.ts spec):
///   import NativeTescoNativeBridge from './NativeTescoNativeBridge';
///   await NativeTescoNativeBridge.onButtonTapped('hello');
@interface TescoNativeBridge : NSObject <NativeTescoNativeBridgeSpec>
@end

NS_ASSUME_NONNULL_END

#endif // __has_include(<React/RCTBridgeModule.h>)
